# Constants for the settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Constants for asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Constants for player movement
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200  # pixels per second

# Constants for shots
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500  # pixels per second
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds between shots

# Menu UI constants
MENU_BUTTON_WIDTH = 200
MENU_BUTTON_HEIGHT = 60
MENU_BUTTON_COLOR = (100, 100, 100)
MENU_BUTTON_HOVER_COLOR = (150, 150, 150)
MENU_BUTTON_ACTIVE_COLOR = (200, 200, 200)
MENU_TEXT_COLOR = (255, 255, 255)
MENU_SPACING = 20
